name: "Deploy to DEV environment."

on:
  # When new commits are pushed onto the main branch.
  push:
    branches:
      - main
    paths:
      - "**"
      - "!infra/**"
      - "!.github/workflows/**"
      - ".github/workflows/deploy-dev.yaml"
      - ".github/workflows/deploy.yaml"
      - "!env/**"

jobs:
  buildAndDeployDev:
    uses: ./.github/workflows/deploy.yaml
    with:
      environmentName: DEV
      tenantId: ${{vars.AZURE_TENANT_ID}}
      azureServicePrincipalClientId: ${{vars.AZURE_SERVICE_PRINCIPAL_CLIENT_ID}}
    secrets:
      azureServicePrincipalClientSecret: ${{secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET}}
