name: "Deploy to DEV environment."

on:
  # When new commits are pushed onto the main branch.
  push:
    branches:
      - main

jobs:
  buildAndDeployDev:
    runs-on: ubuntu-latest
    environment: DEV
    uses: ./.github/workflows/deploy.yaml
    with:
      teamsFxEnvironment: ${{vars.TEAMSFX_ENV_NAME}}
      tenantId: ${{vars.AZURE_TENANT_ID}}
      azureServicePrincipalClientId: ${{vars.AZURE_SERVICE_PRINCIPAL_CLIENT_ID}}
    secrets:
      azureServicePrincipalClientSecret: ${{secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET}}
