name: "Deploy to PROD environment."

on:
  # When the prod tag is pushed.
  push:
    tags:
      - prod

jobs:
  buildAndDeployProd:
    uses: ./.github/workflows/deploy.yaml
    with:
      environmentName: PROD
      tenantId: ${{vars.AZURE_TENANT_ID}}
      azureServicePrincipalClientId: ${{vars.AZURE_SERVICE_PRINCIPAL_CLIENT_ID}}
    secrets:
      azureServicePrincipalClientSecret: ${{secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET}}
