name: "Deploy to PROD environment."

on:
  # When the prod tag is pushed.
  push:
    tags:
      - prod

jobs:
  buildAndDeployProd:
    runs-on: ubuntu-latest
    environment: PROD
    uses: ./.github/workflows/deploy.yaml
    with:
      teamsFxEnvironment: ${{vars.TEAMSFX_ENV_NAME}}
      tenantId: ${{vars.AZURE_TENANT_ID}}
      azureServicePrincipalClientId: ${{vars.AZURE_SERVICE_PRINCIPAL_CLIENT_ID}}
    secrets:
      azureServicePrincipalClientSecret: ${{secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET}}
