name: "Provision and Deploy PROD environment."

on:
  # When the prod tag is pushed.
  push:
    tags:
      - prod

jobs:
  provision-azure-resources-dev:
    runs-on: ubuntu-latest
    environment: PROD
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Read environment variables for the target environment
        run: cat "${{ github.workspace }}/env/.env.prod" | grep -v '^#' >> "$GITHUB_ENV"

      - name: Substitute environment variables in the ARM template parameters file
        run: |
          pushd "${{ github.workspace }}/infra"
          bash generateParametersFromEnv.sh
          popd

      - name: Login to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Provision base resources
        uses: azure/arm-deploy@a1361c2c2cd398621955b16ca32e01c65ea340f5
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          deploymentName: ${{ github.run_number }}
          template: ${{ github.workspace }}/infra/azure.bicep
          parameters: ${{ github.workspace }}/infra/azure.parameters.substituted.json

  buildAndDeployProd:
    uses: ./.github/workflows/deploy.yaml
    with:
      environmentName: PROD
      tenantId: ${{vars.AZURE_TENANT_ID}}
      azureServicePrincipalClientId: ${{vars.AZURE_SERVICE_PRINCIPAL_CLIENT_ID}}
    secrets:
      azureServicePrincipalClientSecret: ${{secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET}}
